# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # using major version aliases

  - 5.6
  - 7.0
  - 7.2

script: phpunit --configuration phpunit.xml --coverage

