# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # using major version aliases

  - 7.2

install:
   - composer install

script: phpunit --configuration phpunit.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)